#!/usr/bin/env python3
"""
driver.py - the ELF end of the pipeline.

The x86-32 lifting itself is pcrecomp's (pcrecomp/tools/lift/lift32_cpu.py,
vendored as a submodule) - one x86 lifter, shared with every PC target rather
than forked per platform. What a Lindbergh game needs on top of a DOS/Win32
binary is exactly three things, and they all live here:

  * the image comes from PT_LOAD segments, not PE sections
  * `int 0x80` / `sysenter` are how the game reaches the kernel, and the stock
    lifter emits `abort()` for both
  * every libc / libGL / libsegaapi call leaves through a PLT stub, so a call
    to a stub address has to become a named HLE call, not a jump into a
    16-byte thunk we have no code for

Usage:
  py -3.11 -m tools recomp <game.elf> <outdir> [0xADDR ...]
"""

import importlib.util
import os
import sys

from ..elf.elf32 import Elf32

_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
_LIFTER_PY = os.path.join(_ROOT, "pcrecomp", "tools", "lift", "lift32_cpu.py")


def load_lifter():
    """Import pcrecomp's lifter by path. It is a script, not an installed
    package, and vendoring it as a submodule is the point - so no sys.path
    surgery, just load the file."""
    if not os.path.exists(_LIFTER_PY):
        raise SystemExit(
            "pcrecomp submodule missing.\n"
            "  git submodule update --init --recursive")
    spec = importlib.util.spec_from_file_location("lift32_cpu", _LIFTER_PY)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def make_lifter_class(base, plt):
    """Subclass pcrecomp's Lifter with the three Linux/ELF differences.

    Subclass rather than patch: pcrecomp stays a clean submodule that other
    projects pull unmodified, and every instruction we do not override keeps
    getting whatever fixes land upstream."""
    from capstone.x86 import X86_OP_IMM

    class LinuxLifter(base.Lifter):
        def translate(self, insn, labels):
            m = insn.mnemonic

            # The kernel boundary. Both forms park the syscall number in eax
            # and its arguments in ebx/ecx/edx/esi/edi/ebp, so the handler
            # reads them straight off the CPU struct.
            if m == "int" and insn.operands and insn.operands[0].imm == 0x80:
                return ["linux_syscall(c);"]
            if m in ("sysenter", "syscall"):
                # Reached via the vDSO's __kernel_vsyscall. The real thing
                # returns to the address the caller stashed, but every caller
                # of the vDSO treats it as an ordinary call, so returning is
                # right here.
                return ["linux_syscall(c); c->esp += 4; return;"]

            # A call to a PLT stub is a call into a library we do not have.
            # Name it and let the runtime decide what to do.
            if m == "call" and insn.operands:
                t = insn.operands[0]
                if t.type == X86_OP_IMM and t.imm in plt:
                    return ["hle_call(c, HLE_%s);" % _ident(plt[t.imm])]

            return super().translate(insn, labels)

    return LinuxLifter


def _ident(name):
    return "".join(ch if ch.isalnum() else "_" for ch in name)


def recompile(elf_path, outdir, addrs=None, bounds=None, split=400):
    """Lift an ELF to C, `split` functions per translation unit.

    Returns (functions lifted, imports referenced)."""
    elf = Elf32(elf_path)
    lift = load_lifter()
    lift.IMAGE_BASE = elf.image_base            # read by Lifter.__init__

    plt = elf.plt_map()
    funcs = dict(bounds or {})
    for addr, (size, name) in elf.functions().items():
        funcs.setdefault(addr, (size, name))
    if not funcs:
        raise SystemExit(
            "%s has no sized STT_FUNC symbols and no bounds file.\n"
            "  A shipped game ELF is stripped; export function bounds from\n"
            "  Ghidra or IDA and pass them with --bounds." % elf_path)

    targets = sorted(addrs) if addrs else sorted(funcs)
    lifter = make_lifter_class(lift, plt)(elf_path, elf.image_size, elf.read_va)

    os.makedirs(outdir, exist_ok=True)
    header = ["/* AUTO-GENERATED by lindberghrecomp - do not edit */",
              '#include "lindbergh_rt.h"', ""]

    # One translation unit per `split` functions. A whole game in a single .c
    # is 1.7 million lines and 156 MB, which no compiler will take in
    # reasonable time or memory - and one file per function is 31,752 compiler
    # invocations. A few hundred per file is the middle that builds.
    chunks, cur, done = [], list(header), []
    for va in targets:
        size, name = funcs.get(va, (0, ""))
        if not size:
            print("[!] no size for %#x, skipped" % va, file=sys.stderr)
            continue
        if name:
            cur.append("/* %s */" % name)
        cur.append(lifter.lift_function(elf.read_va(va, size), va))
        cur.append("")
        done.append(va)
        if split and len(done) % split == 0:
            chunks.append(cur)
            cur = list(header)
    if len(cur) > len(header):
        chunks.append(cur)

    for i, chunk in enumerate(chunks):
        with open(os.path.join(outdir, "recomp_funcs_%04d.c" % i), "w") as f:
            f.write("\n".join(chunk))

    with open(os.path.join(outdir, "recomp_funcs_list.h"), "w") as f:
        f.write("/* AUTO-GENERATED by lindberghrecomp */\n#define LIFTED_FUNCS(X) \\\n")
        f.write(" \\\n".join("    X(%08X)" % a for a in done) + "\n")
    with open(os.path.join(outdir, "recomp_imports.h"), "w") as f:
        f.write("/* AUTO-GENERATED by lindberghrecomp - every PLT import in the ELF.\n"
                "   The runtime provides a body for each; unimplemented ones abort\n"
                "   with their own name, which is how you find what to write next. */\n"
                "#define HLE_IMPORTS(X) \\\n")
        f.write(" \\\n".join('    X(HLE_%s, "%s")' % (_ident(n), n)
                             for n in sorted(set(plt.values()))) + "\n")
    print("[*] %d functions in %d translation units, %d imports"
          % (len(done), len(chunks), len(set(plt.values()))), file=sys.stderr)
    return done, sorted(set(plt.values()))
